language: android

android:
  components:
    - build-tools-21.1.2
    - build-tools-21.0.2
    - android-18
    - android-21
    - extra

# Override the install and test so that we don't run integration tests
install: 
  - ./gradlew assemble

script:
  - ./gradlew :junitTests:test -i
